// Mock data for development - READ ONLY during Phase 2
import type { Prompt } from './types';

export const mockPrompts: Prompt[] = [
  {
    id: '1',
    name: 'AI News Summary',
    description: 'Get the latest AI news',
    content: 'Give me a summary of {{topic}} news from the {{timeframe}}. Focus on: 1. Major breakthroughs 2. Industry announcements 3. Research papers',
    folder: 'Research',
    icon: '📰',
    color: '#3B82F6',
    tags: ['research', 'ai', 'news'],
    variables: [
      { name: 'topic', default: 'AI', required: true },
      { name: 'timeframe', default: 'last week', required: false },
    ],
    auto_paste: true,
    is_favorite: false,
    created_at: '2025-11-30T10:00:00Z',
    updated_at: '2025-11-30T10:00:00Z',
  },
  {
    id: '2',
    name: 'Email Reply Template',
    description: 'Professional email responses',
    content: 'Write a professional email reply to:\n\n{{original_email}}\n\nTone: {{tone}}\nKey points to address:\n{{key_points}}',
    folder: 'Writing',
    icon: '✉️',
    color: '#10B981',
    tags: ['writing', 'email', 'communication'],
    variables: [
      { name: 'original_email', default: '', required: true },
      { name: 'tone', default: 'professional', required: false },
      { name: 'key_points', default: '', required: true },
    ],
    auto_paste: false,
    is_favorite: true,
    created_at: '2025-11-29T15:30:00Z',
    updated_at: '2025-11-29T15:30:00Z',
  },
  {
    id: '3',
    name: 'Code Review Checklist',
    description: 'Systematic code review steps',
    content: 'Review this code:\n\n{{code}}\n\nCheck for:\n- SOLID principles\n- Security vulnerabilities\n- Performance issues\n- Test coverage\n- Documentation',
    folder: 'Coding',
    icon: '💻',
    color: '#F59E0B',
    tags: ['coding', 'review', 'quality'],
    variables: [
      { name: 'code', default: '', required: true },
    ],
    auto_paste: true,
    is_favorite: true,
    created_at: '2025-11-28T09:00:00Z',
    updated_at: '2025-11-28T09:00:00Z',
  },
  {
    id: '4',
    name: 'Meeting Notes Template',
    description: 'Structured meeting documentation',
    content: '# Meeting Notes - {{date}}\n\n## Attendees\n{{attendees}}\n\n## Agenda\n{{agenda}}\n\n## Discussion\n\n## Action Items\n\n## Next Steps',
    folder: 'Work',
    icon: '📝',
    color: '#8B5CF6',
    tags: ['work', 'meetings', 'notes'],
    variables: [
      { name: 'date', default: new Date().toISOString().split('T')[0], required: false },
      { name: 'attendees', default: '', required: true },
      { name: 'agenda', default: '', required: true },
    ],
    auto_paste: false,
    is_favorite: false,
    created_at: '2025-11-27T14:00:00Z',
    updated_at: '2025-11-27T14:00:00Z',
  },
  {
    id: '5',
    name: 'Brainstorm Ideas',
    description: 'Generate creative solutions',
    content: 'Generate 10 creative ideas for: {{problem}}\n\nContext: {{context}}\n\nConstraints: {{constraints}}\n\nFor each idea, provide:\n1. Title\n2. Description\n3. Pros/Cons\n4. Implementation difficulty',
    folder: 'Creative',
    icon: '🌟',
    color: '#EC4899',
    tags: ['creative', 'brainstorm', 'ideas'],
    variables: [
      { name: 'problem', default: '', required: true },
      { name: 'context', default: '', required: false },
      { name: 'constraints', default: 'None', required: false },
    ],
    auto_paste: true,
    is_favorite: false,
    created_at: '2025-11-26T11:00:00Z',
    updated_at: '2025-11-26T11:00:00Z',
  },
];
